"""
coordination_schema.py
======================
SIMP Coordination Intent Schema — v1.0.0
CoWork artifact | Branch: feature/coordination-layer

Purpose:
    Provides a machine-readable, self-describing schema for "coordination intents" —
    meta-work intents emitted by higher-level orchestration agents (Perplexity Computer,
    Claude CoWork) that describe system improvements, test results, proposals, and
    handoffs between agents.

    These are NOT trade intents. They flow through SIMP purely as coordination artifacts
    and should never trigger execution in KashClaw or QuantumArb.

Design notes:
    - Implemented with stdlib dataclasses to match existing simp/intent.py style.
    - Zero new dependencies. Upgrades trivially to Pydantic (see _pydantic_compat note).
    - All fields are optional except the 4 required identity fields.
    - `requires_human_review=True` by default. A coordination agent must explicitly
      set it to False only after triple-verification passes.

Usage:
    from simp.models.coordination_schema import (
        CoordinationIntent,
        CoordinationCategory,
        VerificationStatus,
    )

    intent = CoordinationIntent.create(
        category=CoordinationCategory.PROPOSAL,
        originator="cowork",
        summary="Add capabilities field to agent registration",
        affected_agents=["simp_router", "bullbear_predictor"],
        affected_files=["simp/server/broker.py"],
        roadmap_items=["Day 4 - Multi-Agent Orchestration"],
    )

    # Serialize to dict (for SIMP routing or file artifact)
    payload = intent.to_dict()

    # Write as coordination artifact
    intent.write_artifact("/path/to/signals/output/")

    # Validate a raw dict (e.g. loaded from JSON file)
    loaded = CoordinationIntent.from_dict(payload)
"""

from __future__ import annotations

import dataclasses
import json
import os
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class CoordinationCategory(str, Enum):
    """The category of a coordination intent."""
    PROPOSAL       = "proposal"        # Design or architecture proposal — not yet applied
    TEST_RESULT    = "test_result"     # Outcome of a triple-verification test run
    STATUS_REPORT  = "status_report"   # Point-in-time system health snapshot
    CHANGE_REQUEST = "change_request"  # Code/config change ready for human review
    HANDOFF        = "handoff"         # State transfer between CoWork and Perplexity
    OBSERVATION    = "observation"     # Passive observation of system behavior
    INCIDENT       = "incident"        # Something unexpected or potentially broken


class VerificationStatus(str, Enum):
    """How thoroughly a proposed change has been verified (per SIMP triple-verification policy)."""
    NONE          = "none"           # Not yet verified
    STATIC_REVIEW = "static_review"  # Code/diff reviewed manually
    LOCAL_TEST    = "local_test"     # Tested locally with safe inputs
    E2E_TEST      = "e2e_test"       # Routed through SIMP with multiple agents
    TRIPLE        = "triple_verified" # All three gates passed — safe to review for merge


class CoordinationOriginator(str, Enum):
    """Which coordination agent produced this intent."""
    COWORK      = "cowork"
    PERPLEXITY  = "perplexity"
    HUMAN       = "human"           # For manually authored entries
    SYSTEM      = "system"          # Auto-generated by a watcher or health-check process


# ---------------------------------------------------------------------------
# Core dataclass
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class CoordinationIntent:
    """
    A SIMP coordination intent — a first-class artifact describing meta-work
    (system improvements, test results, proposals) rather than trade activity.

    Required fields:
        coordination_id  — Globally unique ID for this entry (auto-generated UUID4)
        category         — What kind of coordination action this describes
        originator       — Which agent produced this intent
        summary          — Human-readable one-line summary

    All other fields are optional and additive.
    """

    # --- Identity (required) ---
    coordination_id: str
    category: CoordinationCategory
    originator: str          # CoordinationOriginator value or free-form agent_id
    summary: str

    # --- Timestamps ---
    timestamp: str = dataclasses.field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # --- Scope ---
    affected_agents: List[str] = dataclasses.field(default_factory=list)
    affected_files: List[str] = dataclasses.field(default_factory=list)
    roadmap_items: List[str] = dataclasses.field(default_factory=list)

    # --- Verification ---
    verification_status: VerificationStatus = VerificationStatus.NONE
    requires_human_review: bool = True

    # --- Git correlation ---
    git_branch: Optional[str] = None
    git_commit: Optional[str] = None       # Populated after commit is made

    # --- Freeform details ---
    details: Dict[str, Any] = dataclasses.field(default_factory=dict)

    # --- SIMP routing metadata (mirrors SimpIntent fields for broker compatibility) ---
    intent_type: str = "coordination"      # Always "coordination" — never executes a trade
    source_agent: str = ""                 # Populated from originator on create()
    target_agent: str = "simp_router"      # Default: log to router; change for specific agent

    # --- Schema versioning ---
    schema_version: str = "1.0.0"

    # ---------------------------------------------------------------------------
    # Factory
    # ---------------------------------------------------------------------------

    @classmethod
    def create(
        cls,
        category: CoordinationCategory,
        originator: str,
        summary: str,
        *,
        affected_agents: Optional[List[str]] = None,
        affected_files: Optional[List[str]] = None,
        roadmap_items: Optional[List[str]] = None,
        verification_status: VerificationStatus = VerificationStatus.NONE,
        requires_human_review: bool = True,
        git_branch: Optional[str] = None,
        git_commit: Optional[str] = None,
        target_agent: str = "simp_router",
        details: Optional[Dict[str, Any]] = None,
    ) -> "CoordinationIntent":
        """
        Preferred factory method. Generates a UUID4 coordination_id and
        auto-populates source_agent from originator.
        """
        coordination_id = f"coord-{uuid.uuid4().hex[:12]}"
        return cls(
            coordination_id=coordination_id,
            category=category,
            originator=originator,
            summary=summary,
            source_agent=originator,
            target_agent=target_agent,
            affected_agents=affected_agents or [],
            affected_files=affected_files or [],
            roadmap_items=roadmap_items or [],
            verification_status=verification_status,
            requires_human_review=requires_human_review,
            git_branch=git_branch,
            git_commit=git_commit,
            details=details or {},
        )

    # ---------------------------------------------------------------------------
    # Serialization
    # ---------------------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-serializable dict of this coordination intent."""
        d = dataclasses.asdict(self)
        # Convert enum values to their string representation
        d["category"] = self.category.value if isinstance(self.category, CoordinationCategory) else self.category
        d["verification_status"] = (
            self.verification_status.value
            if isinstance(self.verification_status, VerificationStatus)
            else self.verification_status
        )
        return d

    def to_json(self, indent: int = 2) -> str:
        """Return a pretty-printed JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CoordinationIntent":
        """
        Deserialize from a dict (e.g. loaded from a JSON artifact file).
        Validates required fields and coerces enum values.
        Raises ValueError on missing required fields or unrecognized enum values.
        """
        required = ["coordination_id", "category", "originator", "summary"]
        missing = [f for f in required if not data.get(f)]
        if missing:
            raise ValueError(f"CoordinationIntent missing required fields: {missing}")

        # Coerce enums
        try:
            category = CoordinationCategory(data["category"])
        except ValueError as e:
            valid = [c.value for c in CoordinationCategory]
            raise ValueError(f"Invalid category '{data['category']}'. Valid: {valid}") from e

        verification_status = VerificationStatus.NONE
        if data.get("verification_status"):
            try:
                verification_status = VerificationStatus(data["verification_status"])
            except ValueError as e:
                valid = [v.value for v in VerificationStatus]
                raise ValueError(
                    f"Invalid verification_status '{data['verification_status']}'. Valid: {valid}"
                ) from e

        return cls(
            coordination_id=data["coordination_id"],
            category=category,
            originator=data["originator"],
            summary=data["summary"],
            timestamp=data.get("timestamp", datetime.now(timezone.utc).isoformat()),
            affected_agents=data.get("affected_agents", []),
            affected_files=data.get("affected_files", []),
            roadmap_items=data.get("roadmap_items", []),
            verification_status=verification_status,
            requires_human_review=data.get("requires_human_review", True),
            git_branch=data.get("git_branch"),
            git_commit=data.get("git_commit"),
            details=data.get("details", {}),
            intent_type=data.get("intent_type", "coordination"),
            source_agent=data.get("source_agent", data["originator"]),
            target_agent=data.get("target_agent", "simp_router"),
            schema_version=data.get("schema_version", "1.0.0"),
        )

    @classmethod
    def from_json(cls, json_str: str) -> "CoordinationIntent":
        """Deserialize from a JSON string."""
        return cls.from_dict(json.loads(json_str))

    @classmethod
    def from_file(cls, path: str) -> "CoordinationIntent":
        """Load a coordination intent from a JSON file path."""
        with open(path, "r", encoding="utf-8") as f:
            return cls.from_dict(json.load(f))

    # ---------------------------------------------------------------------------
    # Artifact persistence
    # ---------------------------------------------------------------------------

    def write_artifact(self, output_dir: str) -> str:
        """
        Write this coordination intent as a JSON artifact to output_dir,
        using the naming convention: coordination_<coordination_id>.json

        Returns the full path of the written file.

        This is intentionally separate from BullBear signal/intent files to avoid
        the BullBear watcher mistaking coordination artifacts for trade signals.
        Recommendation: write to signals/output/ but prefix with 'coordination_'.
        """
        os.makedirs(output_dir, exist_ok=True)
        filename = f"coordination_{self.coordination_id}.json"
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.to_json())
        return path

    # ---------------------------------------------------------------------------
    # Validation helpers
    # ---------------------------------------------------------------------------

    def validate(self) -> List[str]:
        """
        Run field-level validation. Returns a list of warning strings (empty = clean).
        Does NOT raise — callers decide whether to treat warnings as errors.
        """
        warnings = []
        if not self.summary.strip():
            warnings.append("summary is blank")
        if self.intent_type != "coordination":
            warnings.append(f"intent_type should be 'coordination', got '{self.intent_type}'")
        if (
            self.verification_status == VerificationStatus.TRIPLE
            and self.requires_human_review
        ):
            warnings.append(
                "verification_status is triple_verified but requires_human_review is True. "
                "Consider setting requires_human_review=False after human sign-off."
            )
        if self.category == CoordinationCategory.CHANGE_REQUEST and not self.affected_files:
            warnings.append("change_request category should list at least one affected_files entry")
        if self.category == CoordinationCategory.HANDOFF and not self.details:
            warnings.append("handoff category should include state details in the 'details' field")
        return warnings

    def is_safe_to_apply(self) -> bool:
        """
        Returns True only if this coordination intent has passed triple verification
        AND has been explicitly marked as not requiring human review.
        Hard gate before any automated code application.
        """
        return (
            self.verification_status == VerificationStatus.TRIPLE
            and not self.requires_human_review
        )

    # ---------------------------------------------------------------------------
    # Display
    # ---------------------------------------------------------------------------

    def __str__(self) -> str:
        review_flag = " [NEEDS HUMAN REVIEW]" if self.requires_human_review else " [CLEARED]"
        return (
            f"CoordinationIntent({self.coordination_id}) "
            f"[{self.category.value}] "
            f"by={self.originator} "
            f"verify={self.verification_status.value}"
            f"{review_flag}: {self.summary[:80]}"
        )


# ---------------------------------------------------------------------------
# JSON Schema export (stdlib-only, no jsonschema dependency)
# ---------------------------------------------------------------------------

def export_json_schema() -> Dict[str, Any]:
    """
    Returns a JSON Schema (draft-07) representation of CoordinationIntent.
    Used to generate docs/coordination-schema.json.
    """
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://github.com/therealcryptrillionaire456/SIMP/schemas/coordination_intent.json",
        "title": "CoordinationIntent",
        "description": (
            "A SIMP meta-work intent emitted by coordination agents (CoWork, Perplexity). "
            "Describes system improvements, test results, proposals, and handoffs. "
            "intent_type is always 'coordination' and must never trigger trade execution."
        ),
        "type": "object",
        "required": ["coordination_id", "category", "originator", "summary"],
        "properties": {
            "coordination_id": {
                "type": "string",
                "description": "Unique ID for this coordination entry (UUID4 hex prefixed with 'coord-')",
                "pattern": "^coord-[a-f0-9]{12}$",
                "example": "coord-a1b2c3d4e5f6"
            },
            "category": {
                "type": "string",
                "enum": [c.value for c in CoordinationCategory],
                "description": "Category of coordination action"
            },
            "originator": {
                "type": "string",
                "description": "Agent ID or coordination agent name that produced this intent",
                "example": "cowork"
            },
            "summary": {
                "type": "string",
                "description": "Human-readable one-line summary of the coordination action",
                "minLength": 1,
                "maxLength": 500
            },
            "timestamp": {
                "type": "string",
                "format": "date-time",
                "description": "ISO8601 UTC timestamp of intent creation"
            },
            "affected_agents": {
                "type": "array",
                "items": {"type": "string"},
                "description": "SIMP agent IDs affected by this coordination action",
                "example": ["bullbear_predictor", "kashclaw"]
            },
            "affected_files": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Relative file paths in the SIMP repo affected by this action",
                "example": ["simp/server/broker.py", "docs/coordination-log.md"]
            },
            "roadmap_items": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Roadmap items (from HEARTBEAT.md or PROGRESS.md) addressed",
                "example": ["Day 4 - Multi-Agent Orchestration"]
            },
            "verification_status": {
                "type": "string",
                "enum": [v.value for v in VerificationStatus],
                "default": "none",
                "description": "Triple-verification gate status"
            },
            "requires_human_review": {
                "type": "boolean",
                "default": True,
                "description": "If True, a human must review before this change can be applied"
            },
            "git_branch": {
                "type": ["string", "null"],
                "description": "Git branch name for this change, if applicable",
                "example": "feature/coordination-layer"
            },
            "git_commit": {
                "type": ["string", "null"],
                "description": "Git commit hash, populated after merge",
                "example": "abc1234"
            },
            "details": {
                "type": "object",
                "description": "Freeform key-value payload for category-specific detail",
                "additionalProperties": True
            },
            "intent_type": {
                "type": "string",
                "const": "coordination",
                "description": "Always 'coordination'. Must never be changed to a trade type."
            },
            "source_agent": {
                "type": "string",
                "description": "SIMP source_agent field — mirrors originator for broker compatibility"
            },
            "target_agent": {
                "type": "string",
                "default": "simp_router",
                "description": "SIMP target_agent field — defaults to simp_router for logging"
            },
            "schema_version": {
                "type": "string",
                "default": "1.0.0",
                "description": "Schema version for forward-compatibility"
            }
        },
        "additionalProperties": False
    }
