"""
Integration tests for the payment processing system

Tests the end-to-end flow of payment processing, including:
- Payment service
- Billing service  
- Refund service
- Subscription service
- Payment analytics
"""

import pytest
import asyncio
from datetime import datetime, timedelta
from unittest.mock import AsyncMock, MagicMock, patch
import sys
import os

# Add the app directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../app'))

from services.payment_service import (
    PaymentService,
    PaymentResult,
    CustomerInfo,
    SubscriptionPlan,
    MockStripeProvider,
    create_mock_payment_service
)
from services.billing_service import BillingService
from services.refund_service import RefundService, RefundStatus, RefundReason
from services.subscription_service import SubscriptionService
from services.payment_analytics_service import PaymentAnalyticsService, TimePeriod


class TestPaymentIntegration:
    """Integration tests for payment processing system"""
    
    @pytest.fixture
    def mock_payment_service(self):
        """Create a mock payment service for testing"""
        return create_mock_payment_service()
    
    @pytest.fixture
    def billing_service(self, mock_payment_service):
        """Create a billing service with mock payment service"""
        return BillingService(payment_service=mock_payment_service)
    
    @pytest.fixture
    def refund_service(self, mock_payment_service, billing_service):
        """Create a refund service with dependencies"""
        return RefundService(
            payment_service=mock_payment_service,
            billing_service=billing_service
        )
    
    @pytest.fixture
    def subscription_service(self):
        """Create a subscription service"""
        return SubscriptionService()
    
    @pytest.fixture
    def analytics_service(self):
        """Create a payment analytics service"""
        return PaymentAnalyticsService()
    
    @pytest.fixture
    def sample_customer_info(self):
        """Create sample customer info for testing"""
        return CustomerInfo(
            customer_id="",  # Will be generated by payment service
            email="test@example.com",
            name="Test Customer",
            phone="+1234567890",
            billing_address={
                "line1": "123 Test St",
                "city": "Test City",
                "state": "TS",
                "postal_code": "12345",
                "country": "US"
            },
            shipping_address={
                "line1": "123 Test St",
                "city": "Test City",
                "state": "TS",
                "postal_code": "12345",
                "country": "US"
            },
            metadata={"source": "test"}
        )
    
    @pytest.fixture
    def sample_invoice_data(self):
        """Create sample invoice data for testing"""
        return {
            "subscription_id": "sub_test_123",
            "user_id": "user_123",
            "amount": 99.99,
            "currency": "USD",
            "description": "Monthly subscription",
            "period_start": datetime.utcnow(),
            "period_end": datetime.utcnow() + timedelta(days=30),
            "due_days": 7
        }
    
    @pytest.mark.asyncio
    async def test_end_to_end_payment_flow(self, mock_payment_service, billing_service, 
                                         sample_customer_info, sample_invoice_data):
        """Test complete end-to-end payment flow"""
        # 1. Initialize payment service
        await mock_payment_service.initialize()
        assert mock_payment_service.is_initialized is True
        
        # 2. Create customer
        success, customer_id, message = await mock_payment_service.create_customer(
            email=sample_customer_info.email,
            name=sample_customer_info.name,
            phone=sample_customer_info.phone,
            billing_address=sample_customer_info.billing_address,
            shipping_address=sample_customer_info.shipping_address,
            metadata=sample_customer_info.metadata
        )
        assert success is True
        assert customer_id is not None
        
        # 3. Add payment method
        success, payment_method_id, message = await mock_payment_service.add_payment_method(
            customer_id=customer_id,
            payment_data={
                "type": "card",
                "card_brand": "visa",
                "card_last4": "4242",
                "card_exp_month": 12,
                "card_exp_year": 2025,
                "billing_address": sample_customer_info.billing_address
            }
        )
        assert success is True
        assert payment_method_id is not None
        
        # 4. Create invoice
        success, invoice, message = await billing_service.create_invoice(
            **sample_invoice_data
        )
        assert success is True
        assert invoice is not None
        assert invoice.status.value == "open"  # Invoices are created as OPEN, not DRAFT
        
        # 5. Process payment
        payment_result = await mock_payment_service.process_payment(
            customer_id=customer_id,
            payment_method_id=payment_method_id,
            amount=invoice.amount,
            currency=invoice.currency,
            description=invoice.description,
            metadata={"invoice_id": invoice.invoice_id}
        )
        assert payment_result.success is True
        assert payment_result.transaction_id is not None
        
        # 6. Mark invoice as paid
        success, receipt, message = await billing_service.mark_invoice_paid(
            invoice_id=invoice.invoice_id,
            transaction_id=payment_result.transaction_id,
            payment_method="credit_card"
        )
        assert success is True
        assert receipt is not None
        assert receipt.status.value == "completed"
        
        # 7. Verify payment status
        payment_status = await mock_payment_service.get_payment_status(
            transaction_id=payment_result.transaction_id
        )
        assert payment_status is not None
        assert payment_status["status"] == "succeeded"
        
        print(f"✅ End-to-end payment flow test passed!")
        print(f"   Customer ID: {customer_id}")
        print(f"   Invoice ID: {invoice.invoice_id}")
        print(f"   Transaction ID: {payment_result.transaction_id}")
        print(f"   Receipt ID: {receipt.receipt_id}")
    
    @pytest.mark.asyncio
    async def test_end_to_end_refund_flow(self, mock_payment_service, billing_service,
                                        refund_service, sample_customer_info):
        """Test complete end-to-end refund flow"""
        # 1. Initialize services
        await mock_payment_service.initialize()
        
        # 2. Create customer and actually process a payment
        success, customer_id, _ = await mock_payment_service.create_customer(
            email=sample_customer_info.email,
            name=sample_customer_info.name,
            phone=sample_customer_info.phone,
            billing_address=sample_customer_info.billing_address,
            shipping_address=sample_customer_info.shipping_address,
            metadata=sample_customer_info.metadata
        )
        
        # Add payment method
        success, payment_method_id, _ = await mock_payment_service.add_payment_method(
            customer_id=customer_id,
            payment_data={
                "type": "card",
                "card_brand": "visa",
                "card_last4": "4242",
                "card_exp_month": 12,
                "card_exp_year": 2025,
                "billing_address": sample_customer_info.billing_address
            }
        )
        assert success is True
        
        # Process actual payment
        payment_result = await mock_payment_service.process_payment(
            customer_id=customer_id,
            payment_method_id=payment_method_id,
            amount=49.99,
            currency="USD",
            description="Test purchase",
            metadata={"test": "refund_flow"}
        )
        assert payment_result.success is True
        assert payment_result.transaction_id is not None
        
        # Create invoice and mark as paid with the actual transaction ID
        invoice_data = {
            "subscription_id": "sub_test_456",
            "user_id": "user_123",
            "amount": 49.99,
            "currency": "USD",
            "description": "Test purchase",
            "period_start": datetime.utcnow() - timedelta(days=1),
            "period_end": datetime.utcnow(),
            "due_days": 7
        }
        
        success, invoice, _ = await billing_service.create_invoice(**invoice_data)
        success, receipt, _ = await billing_service.mark_invoice_paid(
            invoice_id=invoice.invoice_id,
            transaction_id=payment_result.transaction_id,
            payment_method="credit_card"
        )
        
        # 3. Request refund
        success, refund_request, message = await refund_service.request_refund(
            receipt_id=receipt.receipt_id,
            user_id="user_123",
            amount=49.99,
            reason=RefundReason.REQUESTED_BY_CUSTOMER,
            reason_details="Changed my mind"
        )
        assert success is True
        assert refund_request is not None
        
        # 4. Verify refund status (should be PENDING due to auto-approval)
        assert refund_request.status == RefundStatus.PENDING
        
        # 5. Process refund
        success, processed_refund, message = await refund_service.process_refund(
            refund_id=refund_request.refund_id,
            processor_id="system"
        )
        assert success is True
        assert processed_refund is not None
        assert processed_refund.status == RefundStatus.COMPLETED
        
        # 6. Verify refund was processed through payment service
        # (In real implementation, this would check the payment service)
        
        print(f"✅ End-to-end refund flow test passed!")
        print(f"   Receipt ID: {receipt.receipt_id}")
        print(f"   Refund ID: {refund_request.refund_id}")
        print(f"   Refund status: {processed_refund.status.value}")
    
    @pytest.mark.asyncio
    async def test_end_to_end_subscription_flow(self, mock_payment_service, 
                                              subscription_service, sample_customer_info):
        """Test complete end-to-end subscription flow"""
        # 1. Initialize payment service
        await mock_payment_service.initialize()
        
        # 2. Create customer
        success, customer_id, _ = await mock_payment_service.create_customer(
            email=sample_customer_info.email,
            name=sample_customer_info.name,
            phone=sample_customer_info.phone,
            billing_address=sample_customer_info.billing_address,
            shipping_address=sample_customer_info.shipping_address,
            metadata=sample_customer_info.metadata
        )
        
        # 3. Get subscription plans
        plans = await subscription_service.get_plans()
        assert len(plans) > 0
        
        # 4. Create subscription
        plan_id = "pro"
        success, subscription, message = await subscription_service.create_subscription(
            user_id="user_123",
            plan_id=plan_id,
            payment_method_id="pm_test_123",
            start_trial=True
        )
        assert success is True
        assert subscription is not None
        assert subscription.plan_id == plan_id
        
        # 5. Verify subscription is active
        assert subscription.is_active() is True
        
        # 6. Process billing cycle
        billing_results = await subscription_service.process_billing_cycle()
        assert isinstance(billing_results, dict)
        assert "processed" in billing_results
        
        # 7. Cancel subscription
        success, message = await subscription_service.cancel_subscription(
            subscription_id=subscription.subscription_id,
            cancel_at_period_end=True
        )
        assert success is True
        
        print(f"✅ End-to-end subscription flow test passed!")
        print(f"   Customer ID: {customer_id}")
        print(f"   Subscription ID: {subscription.subscription_id}")
        print(f"   Plan: {subscription.plan_id}")
    
    @pytest.mark.asyncio
    async def test_payment_analytics_integration(self, analytics_service):
        """Test payment analytics integration"""
        # 1. Get revenue metrics
        revenue_metrics = await analytics_service.get_revenue_metrics(
            period="monthly",
            start_date=datetime.utcnow() - timedelta(days=30),
            end_date=datetime.utcnow()
        )
        assert isinstance(revenue_metrics, list)
        assert len(revenue_metrics) > 0
        
        # 2. Get payment method metrics
        payment_method_metrics = await analytics_service.get_payment_method_metrics(
            start_date=datetime.utcnow() - timedelta(days=30),
            end_date=datetime.utcnow()
        )
        assert isinstance(payment_method_metrics, list)
        
        # 3. Get customer lifetime values
        clv_list = await analytics_service.get_customer_lifetime_values(limit=5)
        assert isinstance(clv_list, list)
        
        # 4. Get financial summary
        financial_summary = await analytics_service.get_financial_summary(
            start_date=datetime.utcnow() - timedelta(days=30),
            end_date=datetime.utcnow()
        )
        assert isinstance(financial_summary, dict)
        assert "summary" in financial_summary
        assert "total_revenue" in financial_summary["summary"]
        assert "total_transactions" in financial_summary["summary"]
        
        # 5. Get forecast
        forecast = await analytics_service.get_forecast(
            periods=3,
            period_type=TimePeriod.MONTHLY
        )
        assert isinstance(forecast, dict)
        assert "forecast" in forecast
        assert len(forecast["forecast"]) > 0
        # Check that forecast items have confidence intervals
        for item in forecast["forecast"]:
            assert "confidence_interval_low" in item
            assert "confidence_interval_high" in item
        
        print(f"✅ Payment analytics integration test passed!")
        print(f"   Revenue metrics: {len(revenue_metrics)} periods")
        print(f"   Financial summary revenue: ${financial_summary.get('total_revenue', 0):.2f}")
    
    @pytest.mark.asyncio
    async def test_error_handling_and_edge_cases(self, mock_payment_service, billing_service):
        """Test error handling and edge cases"""
        # 1. Test payment with invalid amount
        await mock_payment_service.initialize()
        
        # Create customer
        success, customer_id, _ = await mock_payment_service.create_customer(
            email="test@example.com",
            name="Test Customer"
        )
        
        # Add payment method
        success, payment_method_id, _ = await mock_payment_service.add_payment_method(
            customer_id=customer_id,
            payment_data={
                "type": "card",
                "card_brand": "visa",
                "card_last4": "4242",
                "card_exp_month": 12,
                "card_exp_year": 2025
            }
        )
        assert success is True
        
        # Try to process payment with zero amount
        payment_result = await mock_payment_service.process_payment(
            customer_id=customer_id,
            payment_method_id=payment_method_id,
            amount=0,
            currency="USD",
            description="Test payment"
        )
        assert payment_result.success is False
        assert payment_result.error_message is not None
        # Pydantic validation error message
        assert "greater than 0" in payment_result.error_message.lower() or "amount must be positive" in payment_result.error_message.lower()
        
        # 2. Test invoice with past due date (using due_days=0 for immediate due)
        invoice_data = {
            "subscription_id": "sub_test_789",
            "user_id": "user_123",
            "amount": 99.99,
            "currency": "USD",
            "description": "Past due invoice",
            "period_start": datetime.utcnow() - timedelta(days=30),
            "period_end": datetime.utcnow() - timedelta(days=1),
            "due_days": 0  # Immediately due
        }
        
        success, invoice, message = await billing_service.create_invoice(**invoice_data)
        assert success is True  # Should still create invoice with past due date
        
        # 3. Test getting non-existent invoice
        non_existent_invoice = await billing_service.get_invoice("non_existent_123")
        assert non_existent_invoice is None
        
        # 4. Test getting non-existent receipt
        non_existent_receipt = await billing_service.get_receipt("non_existent_123")
        assert non_existent_receipt is None
        
        print(f"✅ Error handling and edge cases test passed!")
        print(f"   Tested: zero amount payment, past due invoice, non-existent records")