# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from simp.server.grpc_proto import simp_pb2 as simp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimpServiceStub(object):
    """── Services ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/simp.SimpService/RegisterAgent',
                request_serializer=simp__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=simp__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.DeregisterAgent = channel.unary_unary(
                '/simp.SimpService/DeregisterAgent',
                request_serializer=simp__pb2.DeregisterAgentRequest.SerializeToString,
                response_deserializer=simp__pb2.DeregisterAgentResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/simp.SimpService/Heartbeat',
                request_serializer=simp__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=simp__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/simp.SimpService/ListAgents',
                request_serializer=simp__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=simp__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/simp.SimpService/GetAgent',
                request_serializer=simp__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=simp__pb2.AgentInfo.FromString,
                _registered_method=True)
        self.SetAgentLifecycle = channel.unary_unary(
                '/simp.SimpService/SetAgentLifecycle',
                request_serializer=simp__pb2.SetAgentLifecycleRequest.SerializeToString,
                response_deserializer=simp__pb2.SetAgentLifecycleResponse.FromString,
                _registered_method=True)
        self.SubmitIntent = channel.unary_unary(
                '/simp.SimpService/SubmitIntent',
                request_serializer=simp__pb2.SubmitIntentRequest.SerializeToString,
                response_deserializer=simp__pb2.SubmitIntentResponse.FromString,
                _registered_method=True)
        self.GetIntentStatus = channel.unary_unary(
                '/simp.SimpService/GetIntentStatus',
                request_serializer=simp__pb2.GetIntentStatusRequest.SerializeToString,
                response_deserializer=simp__pb2.GetIntentStatusResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/simp.SimpService/GetStats',
                request_serializer=simp__pb2.Empty.SerializeToString,
                response_deserializer=simp__pb2.BrokerStats.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/simp.SimpService/Health',
                request_serializer=simp__pb2.HealthRequest.SerializeToString,
                response_deserializer=simp__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/simp.SimpService/StreamLogs',
                request_serializer=simp__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=simp__pb2.StreamLogsResponse.FromString,
                _registered_method=True)


class SimpServiceServicer(object):
    """── Services ───────────────────────────────────────────────────────────────────

    """

    def RegisterAgent(self, request, context):
        """Agent management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAgentLifecycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitIntent(self, request, context):
        """Intent handling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """System
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=simp__pb2.RegisterAgentRequest.FromString,
                    response_serializer=simp__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'DeregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterAgent,
                    request_deserializer=simp__pb2.DeregisterAgentRequest.FromString,
                    response_serializer=simp__pb2.DeregisterAgentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=simp__pb2.HeartbeatRequest.FromString,
                    response_serializer=simp__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=simp__pb2.ListAgentsRequest.FromString,
                    response_serializer=simp__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=simp__pb2.GetAgentRequest.FromString,
                    response_serializer=simp__pb2.AgentInfo.SerializeToString,
            ),
            'SetAgentLifecycle': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAgentLifecycle,
                    request_deserializer=simp__pb2.SetAgentLifecycleRequest.FromString,
                    response_serializer=simp__pb2.SetAgentLifecycleResponse.SerializeToString,
            ),
            'SubmitIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitIntent,
                    request_deserializer=simp__pb2.SubmitIntentRequest.FromString,
                    response_serializer=simp__pb2.SubmitIntentResponse.SerializeToString,
            ),
            'GetIntentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntentStatus,
                    request_deserializer=simp__pb2.GetIntentStatusRequest.FromString,
                    response_serializer=simp__pb2.GetIntentStatusResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=simp__pb2.Empty.FromString,
                    response_serializer=simp__pb2.BrokerStats.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=simp__pb2.HealthRequest.FromString,
                    response_serializer=simp__pb2.HealthResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=simp__pb2.StreamLogsRequest.FromString,
                    response_serializer=simp__pb2.StreamLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simp.SimpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simp.SimpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimpService(object):
    """── Services ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/RegisterAgent',
            simp__pb2.RegisterAgentRequest.SerializeToString,
            simp__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/DeregisterAgent',
            simp__pb2.DeregisterAgentRequest.SerializeToString,
            simp__pb2.DeregisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/Heartbeat',
            simp__pb2.HeartbeatRequest.SerializeToString,
            simp__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/ListAgents',
            simp__pb2.ListAgentsRequest.SerializeToString,
            simp__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/GetAgent',
            simp__pb2.GetAgentRequest.SerializeToString,
            simp__pb2.AgentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAgentLifecycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/SetAgentLifecycle',
            simp__pb2.SetAgentLifecycleRequest.SerializeToString,
            simp__pb2.SetAgentLifecycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/SubmitIntent',
            simp__pb2.SubmitIntentRequest.SerializeToString,
            simp__pb2.SubmitIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/GetIntentStatus',
            simp__pb2.GetIntentStatusRequest.SerializeToString,
            simp__pb2.GetIntentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/GetStats',
            simp__pb2.Empty.SerializeToString,
            simp__pb2.BrokerStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simp.SimpService/Health',
            simp__pb2.HealthRequest.SerializeToString,
            simp__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/simp.SimpService/StreamLogs',
            simp__pb2.StreamLogsRequest.SerializeToString,
            simp__pb2.StreamLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
