#!/usr/bin/env python3.10
"""
send_kloutbot_instruction.py
KLOUTBOT's side of the bridge — posts an instruction to the
'kloutbot_instructions' mesh channel for Goose to pick up and execute.

This script is generated by KLOUTBOT (me) and run by the user once
to inject the instruction into the mesh. Goose then executes it.

Usage:
    python3.10 scripts/kloutbot/send_kloutbot_instruction.py               # send default instruction
    python3.10 scripts/kloutbot/send_kloutbot_instruction.py --file inst.json  # send from file
    python3.10 scripts/kloutbot/send_kloutbot_instruction.py --results     # read back Goose results
"""

import argparse
import json
import time
import uuid
import requests
from datetime import datetime
from pathlib import Path

BROKER_URL   = "http://127.0.0.1:5555"
AGENT_ID     = "kloutbot"
IN_CHANNEL   = "kloutbot_instructions"
OUT_CHANNEL  = "kloutbot_results"


def _post(path, payload):
    try:
        r = requests.post(f"{BROKER_URL}{path}", json=payload, timeout=10)
        r.raise_for_status()
        return r.json() if r.content else {}
    except Exception as e:
        print(f"POST {path} failed: {e}")
        return None


def _setup():
    _post("/agents/register", {
        "agent_id":      AGENT_ID,
        "agent_type":    "kloutbot",
        "endpoint":      "",
        "simp_versions": ["1.0"],
        "capabilities":  ["send_instructions", "read_results"],
        "metadata": {
            "name":    "KLOUTBOT",
            "version": "1.0.0",
        },
    })
    _post("/mesh/subscribe", {"agent_id": AGENT_ID, "channel": OUT_CHANNEL, "simp_versions": ["1.0"]})


def send_instruction(instruction: dict) -> str:
    """Send an instruction to Goose via the mesh. Returns instruction_id."""
    _setup()

    if "instruction_id" not in instruction:
        instruction["instruction_id"] = str(uuid.uuid4())
    if "from" not in instruction:
        instruction["from"] = "kloutbot"
    if "timestamp" not in instruction:
        instruction["timestamp"] = datetime.utcnow().isoformat()

    result = _post("/mesh/send", {
        "sender_id":    AGENT_ID,
        "recipient_id": "goose_kloutbot_bridge",
        "channel":      IN_CHANNEL,
        "payload":      instruction,
    })

    print(f"Instruction sent: {instruction['instruction_id']}")
    print(f"Type: {instruction.get('type')}")
    if instruction.get('description'):
        print(f"Description: {instruction['description']}")
    print(f"Broker response: {result}")
    return instruction["instruction_id"]


def read_results(wait: bool = False, timeout: int = 60) -> list[dict]:
    """Poll kloutbot_results channel for Goose's execution results."""
    _setup()
    print(f"Polling results channel...")

    deadline = time.time() + (timeout if wait else 5)
    all_results = []

    while time.time() < deadline:
        try:
            r = requests.get(
                f"{BROKER_URL}/mesh/poll",
                params={"agent_id": AGENT_ID, "channel": OUT_CHANNEL, "max_messages": 10},
                timeout=10,
            )
            r.raise_for_status()
            poll = r.json() if r.content else {}
        except Exception as e:
            print(f"GET /mesh/poll failed: {e}")
            poll = None
        if poll and isinstance(poll.get("messages"), list):
            for msg in poll["messages"]:
                payload = msg.get("payload", msg)
                all_results.append(payload)
                iid = payload.get("instruction_id", "?")
                result = payload.get("result", {})
                success = result.get("success", "?")
                stdout  = result.get("stdout", "")[:500]
                print(f"\n── Result for {iid} ─────────────────────")
                print(f"  Success: {success}")
                if stdout:
                    print(f"  Output:\n{stdout}")
                if result.get("stderr"):
                    print(f"  Stderr: {result['stderr'][:200]}")
        if all_results or not wait:
            break
        print("  Waiting for Goose to execute... (Ctrl+C to stop)")
        time.sleep(3)

    if not all_results:
        print("No results yet. Run 'python3.10 scripts/kloutbot/kloutbot_bridge.py --execute' in Goose.")
    return all_results


# ── Default instruction: the QIP fix sequence ────────────────────────────────
DEFAULT_INSTRUCTION = {
    "type": "commands",
    "description": "Fix QIP mesh consumer — deploy v2.1, restart clean, verify round-trip",
    "stop_on_failure": False,
    "commands": [
        {
            "type": "bash",
            "cmd": "cp ~/Downloads/quantum_mesh_consumer.py .",
            "description": "Deploy fixed consumer v2.1",
        },
        {
            "type": "bash",
            "cmd": "pkill -f quantum_mesh_consumer 2>/dev/null; sleep 2; "
                   "nohup python3.10 quantum_mesh_consumer.py "
                   "> data/logs/goose/qip.log 2>&1 & echo $!",
            "description": "Restart QIP consumer",
        },
        {
            "type": "bash",
            "cmd": "sleep 6 && tail -20 data/logs/goose/qip.log",
            "description": "Check QIP startup log",
        },
        {
            "type": "bash",
            "cmd": "python3.10 goose_quantum_orchestrator.py --status",
            "description": "QIP health check",
        },
        {
            "type": "bash",
            "cmd": "python3.10 quantum_signal_bridge.py --once",
            "description": "Fire first live revenue signal",
        },
        {
            "type": "diagnostic",
            "name": "mesh_agents",
            "description": "Verify QIP is in mesh routing table",
        },
    ],
}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="KLOUTBOT instruction sender")
    parser.add_argument("--file",    type=str, help="Path to instruction JSON file")
    parser.add_argument("--results", action="store_true", help="Read back results from Goose")
    parser.add_argument("--wait",    action="store_true", help="Wait up to 60s for results")
    args = parser.parse_args()

    if args.results:
        read_results(wait=args.wait)
    elif args.file:
        instruction = json.loads(Path(args.file).read_text())
        send_instruction(instruction)
    else:
        # Send the default QIP fix instruction
        send_instruction(DEFAULT_INSTRUCTION)
        print("\nNow tell Goose: python3.10 scripts/kloutbot/kloutbot_bridge.py --execute")
        print("Then check results: python3.10 scripts/kloutbot/send_kloutbot_instruction.py --results --wait")
