#!/bin/bash
# Daily Compliance Pipeline
# Runs compliance mapping and integrates with existing systems

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "⚖️ Starting daily compliance pipeline..."
echo "📅 Date: $(date)"
echo "📁 Repository: $REPO_ROOT"

# Create directories
mkdir -p compliance_reports
mkdir -p data
mkdir -p logs

LOG_FILE="logs/daily_compliance_$(date +%Y%m%d).log"
echo "📝 Logging to: $LOG_FILE"

# Function to log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Check if Graphify data exists
if [ ! -f ".graphify/simp_graph.json" ]; then
    log "⚠️ Graphify data not found. Compliance mapping may be limited."
fi

# Step 1: Run compliance mapper
log "🔍 Step 1: Scanning legal documents..."
python3.10 tools/compliance_mapper.py --scan 2>&1 | tee -a "$LOG_FILE"

log "🗺️ Step 2: Mapping modules to requirements..."
python3.10 tools/compliance_mapper.py --map 2>&1 | tee -a "$LOG_FILE"

log "📊 Step 3: Generating compliance report..."
python3.10 tools/compliance_mapper.py --report 2>&1 | tee -a "$LOG_FILE"

log "📄 Step 4: Exporting reports..."
python3.10 tools/compliance_mapper.py --export markdown 2>&1 | tee -a "$LOG_FILE"

# Step 5: Integrate with existing systems
log "🎨 Step 5: Integrating with architecture briefs..."
python3.10 tools/compliance_integration.py --enhance-brief 2>&1 | tee -a "$LOG_FILE"

log "📊 Step 6: Generating dashboard data..."
python3.10 tools/compliance_integration.py --dashboard 2>&1 | tee -a "$LOG_FILE"

# Generate summary
log "📋 Generating compliance summary..."
cat > compliance_reports/daily_compliance_summary_$(date +%Y%m%d).md << SUMMARY
# Daily Compliance Summary - $(date +%Y-%m-%d)

## 📊 Pipeline Execution
- **Started**: $(date)
- **Log file**: $LOG_FILE
- **Reports directory**: compliance_reports/

## 🔍 Steps Completed
1. ✅ Legal document scanning
2. ✅ Module-to-requirement mapping  
3. ✅ Compliance report generation
4. ✅ Report export (Markdown)
5. ✅ Architecture brief enhancement
6. ✅ Dashboard data generation

## 📁 Generated Files
$(find compliance_reports -name "*$(date +%Y%m%d)*" -type f -exec basename {} \; | sed 's/^/- /')

## 🎯 Next Actions
1. Review high-priority compliance modules
2. Update module documentation with requirements
3. Add compliance tests where needed
4. Schedule compliance audit

---
*Generated by SIMP Daily Compliance Pipeline*
SUMMARY

# Create latest symlinks
log "🔗 Creating latest symlinks..."
ln -sf "$(find compliance_reports -name "*$(date +%Y%m%d)*.md" | head -1)" compliance_reports/latest_compliance_report.md 2>/dev/null || true
ln -sf "$(find compliance_reports -name "dashboard_data.json" | head -1)" compliance_reports/latest_dashboard_data.json 2>/dev/null || true

log "✅ Daily compliance pipeline complete!"
log "📁 Output directory: compliance_reports/"
log "📋 Summary: compliance_reports/daily_compliance_summary_$(date +%Y%m%d).md"

echo ""
echo "🎉 Daily compliance pipeline executed successfully!"
echo "📊 Check the latest reports:"
echo "   ls -la compliance_reports/latest*"
echo "   cat compliance_reports/latest_compliance_report.md | head -30"
