#!/bin/bash
# Daily Obsidian + Graphify synchronization for SIMP
# Auto-generated by integrate_obsidian_graphify.py

set -e  # Exit on error

# Configuration
SIMP_ROOT="/Users/kaseymarcelle/Downloads/kashclaw (claude rebuild)/simp"
LOG_DIR="${SIMP_ROOT}/logs"
LOG_FILE="${LOG_DIR}/obsidian_sync_$(date +%Y%m%d_%H%M%S).log"
MAX_LOG_FILES=30  # Keep last 30 days of logs

# Create log directory
mkdir -p "$LOG_DIR"

# Function to log messages
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Function to clean up old logs
cleanup_old_logs() {
    log "Cleaning up old log files (keeping last $MAX_LOG_FILES)..."
    cd "$LOG_DIR"
    ls -t obsidian_sync_*.log 2>/dev/null | tail -n +$((MAX_LOG_FILES + 1)) | xargs rm -f 2>/dev/null || true
}

# Start synchronization
log "="*60
log "Starting daily Obsidian + Graphify synchronization"
log "Timestamp: $(date)"
log "SIMP Root: $SIMP_ROOT"
log "Log File: $LOG_FILE"
log "="*60

# Change to SIMP root directory
cd "$SIMP_ROOT"

# Check if integration script exists
if [ ! -f "integrate_obsidian_graphify.py" ]; then
    log "ERROR: Integration script not found: integrate_obsidian_graphify.py"
    exit 1
fi

# Check Python version
PYTHON_VERSION=$(python3.10 --version 2>&1 || echo "Python 3.10 not found")
log "Python version: $PYTHON_VERSION"

if [[ ! "$PYTHON_VERSION" == *"3.10"* ]]; then
    log "WARNING: Python 3.10 not found, using available Python"
    PYTHON_CMD="python3"
else
    PYTHON_CMD="python3.10"
fi

# Run the integration
log "Running integration script..."
if $PYTHON_CMD integrate_obsidian_graphify.py --sync 2>&1 | tee -a "$LOG_FILE"; then
    SYNC_STATUS="SUCCESS"
    log "Synchronization completed successfully"
else
    SYNC_STATUS="FAILED"
    log "ERROR: Synchronization failed"
    
    # Try fallback: direct sync
    log "Attempting fallback sync..."
    OBSIDIAN_ROOT="/Users/kaseymarcelle/stray_goose/SIMP-obsidian-docs"
    if [ -f "$OBSIDIAN_ROOT/sync_with_simp.py" ]; then
        log "Running direct sync script..."
        cd "$OBSIDIAN_ROOT"
        if $PYTHON_CMD sync_with_simp.py 2>&1 | tee -a "$LOG_FILE"; then
            log "Fallback sync completed"
            SYNC_STATUS="PARTIAL_SUCCESS"
        else
            log "ERROR: Fallback sync also failed"
        fi
    fi
fi

# Generate summary report
log "="*60
log "Synchronization Summary"
log "Status: $SYNC_STATUS"
log "Completion Time: $(date)"
log "Log File: $LOG_FILE"

# Check for generated files
OBSIDIAN_ROOT="/Users/kaseymarcelle/stray_goose/SIMP-obsidian-docs"
if [ -d "$OBSIDIAN_ROOT" ]; then
    # Count documentation files
    DOC_COUNT=$(find "$OBSIDIAN_ROOT" -name "*.md" -type f | wc -l)
    log "Documentation Files: $DOC_COUNT"
    
    # Check for diagrams
    VIZ_DIR="$OBSIDIAN_ROOT/Visualizations/System_Graphs/generated"
    if [ -d "$VIZ_DIR" ]; then
        DIAGRAM_COUNT=$(find "$VIZ_DIR" -type f | wc -l)
        log "Generated Diagrams: $DIAGRAM_COUNT"
    else
        log "Generated Diagrams: 0 (directory not found)"
    fi
fi

# Clean up old logs
cleanup_old_logs

# Final status
log "="*60
if [ "$SYNC_STATUS" = "SUCCESS" ] || [ "$SYNC_STATUS" = "PARTIAL_SUCCESS" ]; then
    log "✅ Daily sync completed: $SYNC_STATUS"
    exit 0
else
    log "❌ Daily sync failed"
    exit 1
fi